### ISSUE TITLE
are there plans to support shelly 1, 2 and 4 pro?

### ISSUE THREAD

**Issue by rhamblen** [BrettSheleski/SmartThingsPublic#25]

**Comment by BrettSheleski** [comment]
I believe this is in regards to my Tasmota family of Device Handlers.

As long as the Tasmota firmware is able to run on the device, these device handlers should work.  I may have to do some coding to handle the specific case if the module is running on Shelly devices, but since I do not have any such device it is tough to say if/when this support is coming.

I would suppose the most one would have to do is modify the switch statement where it detects the module type.  Feel free to modify the code and submit a pull request with the necessary changes.

**Comment by rhamblen** [comment]
Thanks
I’m ordering the pro in the new year... it has two useful features I need.
1. I can use a switch from a regular switch... ie make it a 2 gang device. Or three !)
2. I can monitor power

I’ll do a pull in new year when I am ready.
Thanks

**Comment by rhamblen** [comment]
i can confirm the shelly 1 works with tasmota and brett's software.  There are a number of shelly devices which work with tasmota including shelly 1, 1PM, 2 and 2.5.
The 4 pro is on a different platform (processor) so will not work with Tasmota.
There is a solution which I havent fully tested that someone has using the REST API.
